// Code generated by counterfeiter. DO NOT EDIT.
package synchronizerfakes

import (
	"sync"

	"github.com/livekit/server-sdk-go/v2/pkg/synchronizer"
	webrtc "github.com/pion/webrtc/v4"
)

type FakeTrackRemote struct {
	CodecStub        func() webrtc.RTPCodecParameters
	codecMutex       sync.RWMutex
	codecArgsForCall []struct {
	}
	codecReturns struct {
		result1 webrtc.RTPCodecParameters
	}
	codecReturnsOnCall map[int]struct {
		result1 webrtc.RTPCodecParameters
	}
	IDStub        func() string
	iDMutex       sync.RWMutex
	iDArgsForCall []struct {
	}
	iDReturns struct {
		result1 string
	}
	iDReturnsOnCall map[int]struct {
		result1 string
	}
	KindStub        func() webrtc.RTPCodecType
	kindMutex       sync.RWMutex
	kindArgsForCall []struct {
	}
	kindReturns struct {
		result1 webrtc.RTPCodecType
	}
	kindReturnsOnCall map[int]struct {
		result1 webrtc.RTPCodecType
	}
	SSRCStub        func() webrtc.SSRC
	sSRCMutex       sync.RWMutex
	sSRCArgsForCall []struct {
	}
	sSRCReturns struct {
		result1 webrtc.SSRC
	}
	sSRCReturnsOnCall map[int]struct {
		result1 webrtc.SSRC
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTrackRemote) Codec() webrtc.RTPCodecParameters {
	fake.codecMutex.Lock()
	ret, specificReturn := fake.codecReturnsOnCall[len(fake.codecArgsForCall)]
	fake.codecArgsForCall = append(fake.codecArgsForCall, struct {
	}{})
	stub := fake.CodecStub
	fakeReturns := fake.codecReturns
	fake.recordInvocation("Codec", []interface{}{})
	fake.codecMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTrackRemote) CodecCallCount() int {
	fake.codecMutex.RLock()
	defer fake.codecMutex.RUnlock()
	return len(fake.codecArgsForCall)
}

func (fake *FakeTrackRemote) CodecCalls(stub func() webrtc.RTPCodecParameters) {
	fake.codecMutex.Lock()
	defer fake.codecMutex.Unlock()
	fake.CodecStub = stub
}

func (fake *FakeTrackRemote) CodecReturns(result1 webrtc.RTPCodecParameters) {
	fake.codecMutex.Lock()
	defer fake.codecMutex.Unlock()
	fake.CodecStub = nil
	fake.codecReturns = struct {
		result1 webrtc.RTPCodecParameters
	}{result1}
}

func (fake *FakeTrackRemote) CodecReturnsOnCall(i int, result1 webrtc.RTPCodecParameters) {
	fake.codecMutex.Lock()
	defer fake.codecMutex.Unlock()
	fake.CodecStub = nil
	if fake.codecReturnsOnCall == nil {
		fake.codecReturnsOnCall = make(map[int]struct {
			result1 webrtc.RTPCodecParameters
		})
	}
	fake.codecReturnsOnCall[i] = struct {
		result1 webrtc.RTPCodecParameters
	}{result1}
}

func (fake *FakeTrackRemote) ID() string {
	fake.iDMutex.Lock()
	ret, specificReturn := fake.iDReturnsOnCall[len(fake.iDArgsForCall)]
	fake.iDArgsForCall = append(fake.iDArgsForCall, struct {
	}{})
	stub := fake.IDStub
	fakeReturns := fake.iDReturns
	fake.recordInvocation("ID", []interface{}{})
	fake.iDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTrackRemote) IDCallCount() int {
	fake.iDMutex.RLock()
	defer fake.iDMutex.RUnlock()
	return len(fake.iDArgsForCall)
}

func (fake *FakeTrackRemote) IDCalls(stub func() string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = stub
}

func (fake *FakeTrackRemote) IDReturns(result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	fake.iDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeTrackRemote) IDReturnsOnCall(i int, result1 string) {
	fake.iDMutex.Lock()
	defer fake.iDMutex.Unlock()
	fake.IDStub = nil
	if fake.iDReturnsOnCall == nil {
		fake.iDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.iDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeTrackRemote) Kind() webrtc.RTPCodecType {
	fake.kindMutex.Lock()
	ret, specificReturn := fake.kindReturnsOnCall[len(fake.kindArgsForCall)]
	fake.kindArgsForCall = append(fake.kindArgsForCall, struct {
	}{})
	stub := fake.KindStub
	fakeReturns := fake.kindReturns
	fake.recordInvocation("Kind", []interface{}{})
	fake.kindMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTrackRemote) KindCallCount() int {
	fake.kindMutex.RLock()
	defer fake.kindMutex.RUnlock()
	return len(fake.kindArgsForCall)
}

func (fake *FakeTrackRemote) KindCalls(stub func() webrtc.RTPCodecType) {
	fake.kindMutex.Lock()
	defer fake.kindMutex.Unlock()
	fake.KindStub = stub
}

func (fake *FakeTrackRemote) KindReturns(result1 webrtc.RTPCodecType) {
	fake.kindMutex.Lock()
	defer fake.kindMutex.Unlock()
	fake.KindStub = nil
	fake.kindReturns = struct {
		result1 webrtc.RTPCodecType
	}{result1}
}

func (fake *FakeTrackRemote) KindReturnsOnCall(i int, result1 webrtc.RTPCodecType) {
	fake.kindMutex.Lock()
	defer fake.kindMutex.Unlock()
	fake.KindStub = nil
	if fake.kindReturnsOnCall == nil {
		fake.kindReturnsOnCall = make(map[int]struct {
			result1 webrtc.RTPCodecType
		})
	}
	fake.kindReturnsOnCall[i] = struct {
		result1 webrtc.RTPCodecType
	}{result1}
}

func (fake *FakeTrackRemote) SSRC() webrtc.SSRC {
	fake.sSRCMutex.Lock()
	ret, specificReturn := fake.sSRCReturnsOnCall[len(fake.sSRCArgsForCall)]
	fake.sSRCArgsForCall = append(fake.sSRCArgsForCall, struct {
	}{})
	stub := fake.SSRCStub
	fakeReturns := fake.sSRCReturns
	fake.recordInvocation("SSRC", []interface{}{})
	fake.sSRCMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeTrackRemote) SSRCCallCount() int {
	fake.sSRCMutex.RLock()
	defer fake.sSRCMutex.RUnlock()
	return len(fake.sSRCArgsForCall)
}

func (fake *FakeTrackRemote) SSRCCalls(stub func() webrtc.SSRC) {
	fake.sSRCMutex.Lock()
	defer fake.sSRCMutex.Unlock()
	fake.SSRCStub = stub
}

func (fake *FakeTrackRemote) SSRCReturns(result1 webrtc.SSRC) {
	fake.sSRCMutex.Lock()
	defer fake.sSRCMutex.Unlock()
	fake.SSRCStub = nil
	fake.sSRCReturns = struct {
		result1 webrtc.SSRC
	}{result1}
}

func (fake *FakeTrackRemote) SSRCReturnsOnCall(i int, result1 webrtc.SSRC) {
	fake.sSRCMutex.Lock()
	defer fake.sSRCMutex.Unlock()
	fake.SSRCStub = nil
	if fake.sSRCReturnsOnCall == nil {
		fake.sSRCReturnsOnCall = make(map[int]struct {
			result1 webrtc.SSRC
		})
	}
	fake.sSRCReturnsOnCall[i] = struct {
		result1 webrtc.SSRC
	}{result1}
}

func (fake *FakeTrackRemote) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTrackRemote) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ synchronizer.TrackRemote = new(FakeTrackRemote)
